from shared.django.admin import CustomVerboseNamesOfFieldsModelTranslations
from shared.django.customizations import BothHttpAndHttpsSchemaGenerator
from shared.django.models import TimeBaseModel
from shared.django.classes import CustomTranslationOptions, CustomGenericAPIView
from shared.django.pagination import CustomPagination
