# Generated by Django 5.0.6 on 2024-08-30 08:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_law_management_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='law',
            options={'verbose_name': 'Legislative Base', 'verbose_name_plural': 'Legislative Bases'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Management', 'verbose_name_plural': 'Managements'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Provide a detailed description about the organization.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='photo',
            field=models.ImageField(help_text='Upload an image representing the organization.', upload_to='about_us/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='law',
            name='file',
            field=models.FileField(help_text='Upload the law document file.', upload_to='laws/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='law',
            name='law_type',
            field=models.CharField(choices=[('LAW', 'Law'), ('PRESIDENTIAL', 'Presidential'), ('CABINET', 'Cabinet'), ('RAILWAY', 'Railway'), ('SSV', 'SSV')], help_text='Select the type of the law.', max_length=20, verbose_name='Law Type'),
        ),
        migrations.AlterField(
            model_name='law',
            name='link',
            field=models.URLField(help_text='Provide a link to the law document or webpage.', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='law',
            name='name',
            field=models.CharField(help_text='Enter the name of the law.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='management',
            name='administration_type',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('LEADERSHIP', 'Leadership')], help_text='Select the type of administration.', max_length=20, verbose_name='Administration Type'),
        ),
        migrations.AlterField(
            model_name='management',
            name='email',
            field=models.EmailField(help_text='Enter the contact email address.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='management',
            name='file',
            field=models.ImageField(help_text='Upload the profile image of the person.', upload_to='administration/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='management',
            name='full_name',
            field=models.CharField(help_text='Enter the full name of the person.', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='management',
            name='job_description',
            field=models.TextField(help_text='Provide a detailed job description of the person.', verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='management',
            name='permission',
            field=models.TextField(help_text='Specify the permissions or authority held by the person.', verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='management',
            name='phone_number',
            field=models.CharField(help_text='Enter the contact phone number.', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='management',
            name='reception_day',
            field=models.CharField(help_text='Enter the reception day for public visits.', max_length=255, verbose_name='Reception Day'),
        ),
        migrations.AlterField(
            model_name='management',
            name='role',
            field=models.CharField(help_text='Enter the role or position of the person.', max_length=255, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='image',
            field=models.ImageField(help_text='Upload an image representing the structure of the organization.', upload_to='structure/', verbose_name='Structure Image'),
        ),
        migrations.AlterModelTable(
            name='law',
            table='law',
        ),
        migrations.AlterModelTable(
            name='management',
            table='management',
        ),
        migrations.AlterModelTable(
            name='structure',
            table='structure',
        ),
    ]
