# Generated by Django 5.0.6 on 2024-08-30 08:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_law_options_alter_management_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Provide a detailed description about the organization.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Provide a detailed description about the organization.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Provide a detailed description about the organization.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='law',
            name='name_en',
            field=models.CharField(help_text='Enter the name of the law.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='law',
            name='name_ru',
            field=models.CharField(help_text='Enter the name of the law.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='law',
            name='name_uz',
            field=models.CharField(help_text='Enter the name of the law.', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='management',
            name='full_name_en',
            field=models.CharField(help_text='Enter the full name of the person.', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='management',
            name='full_name_ru',
            field=models.CharField(help_text='Enter the full name of the person.', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='management',
            name='full_name_uz',
            field=models.CharField(help_text='Enter the full name of the person.', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='management',
            name='job_description_en',
            field=models.TextField(help_text='Provide a detailed job description of the person.', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='management',
            name='job_description_ru',
            field=models.TextField(help_text='Provide a detailed job description of the person.', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='management',
            name='job_description_uz',
            field=models.TextField(help_text='Provide a detailed job description of the person.', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='management',
            name='permission_en',
            field=models.TextField(help_text='Specify the permissions or authority held by the person.', null=True, verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='management',
            name='permission_ru',
            field=models.TextField(help_text='Specify the permissions or authority held by the person.', null=True, verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='management',
            name='permission_uz',
            field=models.TextField(help_text='Specify the permissions or authority held by the person.', null=True, verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_day_en',
            field=models.CharField(help_text='Enter the reception day for public visits.', max_length=255, null=True, verbose_name='Reception Day'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_day_ru',
            field=models.CharField(help_text='Enter the reception day for public visits.', max_length=255, null=True, verbose_name='Reception Day'),
        ),
        migrations.AddField(
            model_name='management',
            name='reception_day_uz',
            field=models.CharField(help_text='Enter the reception day for public visits.', max_length=255, null=True, verbose_name='Reception Day'),
        ),
        migrations.AddField(
            model_name='management',
            name='role_en',
            field=models.CharField(help_text='Enter the role or position of the person.', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='management',
            name='role_ru',
            field=models.CharField(help_text='Enter the role or position of the person.', max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='management',
            name='role_uz',
            field=models.CharField(help_text='Enter the role or position of the person.', max_length=255, null=True, verbose_name='Role'),
        ),
    ]
