# Generated by Django 5.0.6 on 2024-09-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('management', '0005_tags_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'photo',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='photo',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='main_photo',
            field=models.ImageField(default='', help_text='Upload an image representing the organization.',
                                    upload_to='about_us/', verbose_name='Main photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='main_photo',
            field=models.ImageField(upload_to='main_photos/', verbose_name='Main main_photo'),
        ),
        migrations.CreateModel(
            name='AboutUsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.aboutus',
                                               verbose_name='About Us')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.photo',
                                            verbose_name='photo')),
            ],
            options={
                'verbose_name': 'About Us Photo',
                'verbose_name_plural': 'About Us Photos',
                'db_table': 'about_us_photos',
                'unique_together': {('about_us', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='aboutus',
            name='photos',
            field=models.ManyToManyField(related_name='about_us_photos', through='management.AboutUsPhoto',
                                         to='management.photo', verbose_name='Photos'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
