# Generated by Django 5.0.6 on 2024-09-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_content_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
