# Generated by Django 5.0.6 on 2024-09-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_content_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='photos',
        ),
        migrations.AlterField(
            model_name='aboutusphoto',
            name='photo',
            field=models.ImageField(upload_to='about_us/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='contentphoto',
            name='photo',
            field=models.ImageField(upload_to='contents/photos/main/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='content',
            name='main_photo',
            field=models.ImageField(upload_to='contents/photos/main', verbose_name='Main main_photo'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
