# Generated by Django 5.0.6 on 2024-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_aboutusphoto_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='aboutusphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='contentphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='law',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='management',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='structure',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
    ]
