# Generated by Django 5.0.6 on 2024-09-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_aboutus_options_alter_aboutusphoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='management',
            name='job_description_en',
        ),
        migrations.RemoveField(
            model_name='management',
            name='job_description_ru',
        ),
        migrations.RemoveField(
            model_name='management',
            name='job_description_uz',
        ),
    ]
