# Generated by Django 5.0.6 on 2024-09-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_management_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='job_description',
            field=models.TextField(default='example', help_text='Provide a detailed job description of the person.', verbose_name='Job Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='management',
            name='job_description_en',
            field=models.TextField(help_text='Provide a detailed job description of the person.', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='management',
            name='job_description_ru',
            field=models.TextField(help_text='Provide a detailed job description of the person.', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='management',
            name='job_description_uz',
            field=models.TextField(help_text='Provide a detailed job description of the person.', null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='law',
            name='link',
            field=models.URLField(blank=True, help_text='Provide a link to the law document or webpage.', null=True, verbose_name='Link'),
        ),
    ]
