# Generated by Django 5.0.6 on 2024-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_management_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('creator', models.CharField(max_length=128)),
                ('owner', models.CharField(default=None, help_text="Owner's username from UMS", max_length=128, null=True)),
                ('slug_name', models.CharField(max_length=128, unique=True)),
                ('inn', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'apps_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSpecialistBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('lastname', models.CharField(blank=True, max_length=128)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'apps_specialist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSpecialistCatTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek'), ('en', 'English')], max_length=8)),
            ],
            options={
                'db_table': 'apps_specialistcattranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSpecialistsCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apps_specialistscat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSpecialistTimeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('device', models.CharField(help_text='equipment_code from PMS', max_length=26)),
                ('is_overtime', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'apps_specialisttimetracker',
                'managed': False,
            },
        ),
    ]
