# Generated by Django 5.0.6 on 2024-10-07 05:43

import management.models.pms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_appsorganization_appsspecialistbms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProductCategoryTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russsian'), ('uz', 'Uzbek')], max_length=8)),
            ],
            options={
                'db_table': 'apps_categorytranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hide_from_orgs', models.BooleanField()),
                ('hide_from_users', models.BooleanField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('first_level_score', models.IntegerField()),
                ('level_progress_by', models.IntegerField()),
            ],
            options={
                'db_table': 'apps_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsCurrency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'apps_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(default=None, null=True, upload_to=management.models.pms.UploadPath('group'))),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('vat', models.FloatField(default=12.0)),
                ('discount', models.FloatField(default=0)),
                ('cashback', models.FloatField(default=0)),
                ('cancel_fine', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apps_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsHashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'apps_hashtag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsHashtagCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
            options={
                'db_table': 'apps_hashtagcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsManufacturer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('org', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'apps_manufacturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsPlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('day', models.IntegerField()),
                ('value', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apps_planhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('bar_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_sell', models.BooleanField()),
                ('measure', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'apps_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'apps_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'apps_productstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductToGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'apps_producttogroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductToOrganization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=128)),
                ('status', models.IntegerField()),
                ('remains', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('cashback', models.IntegerField(blank=True, null=True)),
                ('cashback_type', models.CharField(choices=[('percentage', 'Percentage'), ('som', 'Som')], default='percentage', max_length=255)),
                ('cancel_fine', models.IntegerField(blank=True, null=True)),
                ('rec_cashback', models.IntegerField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(default=None, null=True)),
                ('delay_cancel_fine', models.IntegerField(blank=True, null=True)),
                ('vat', models.IntegerField(blank=True, null=True)),
                ('is_official', models.BooleanField()),
                ('dependence_sell', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_producttoorganization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductToSpecialist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialist', models.BigIntegerField()),
            ],
            options={
                'db_table': 'apps_producttospecialist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductTranslate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('lang', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'apps_producttranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'apps_producttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsRegion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField()),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsRegionTranslate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('lang', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'apps_regiontranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(help_text='org slug from BMS', max_length=128)),
                ('spec_cat', models.IntegerField(help_text='specialist category id from BMS')),
                ('auto', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('lastname', models.CharField(default=None, max_length=128, null=True)),
                ('avatar', models.CharField(default=None, max_length=1024, null=True)),
                ('status', models.IntegerField(default=1)),
                ('is_great', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'apps_specialist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSpecialistHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'apps_specialisthashtag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSurcharge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('value', models.FloatField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'apps_surcharge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsSurchargesInProductToOrganization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'apps_surchargesinproducttoorganization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsUnitProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'apps_unitproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsUnitProductTranslate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('lang', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'apps_unitproducttranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('avatar', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('pinfl', models.CharField(blank=True, default=None, max_length=14, null=True)),
            ],
            options={
                'db_table': 'apps_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UMSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hide_from_orgs', models.BooleanField(default=True)),
                ('hide_from_users', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('first_level_score', models.PositiveIntegerField(default=5)),
                ('level_progress_by', models.PositiveIntegerField(default=3)),
                ('creator', models.CharField(default=None, help_text='username from UMS', max_length=128, null=True)),
            ],
            options={
                'db_table': 'apps_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UMSCategoryTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'apps_categorytranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UMSSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(help_text='org slug from BMS', max_length=128)),
                ('spec_cat', models.IntegerField(help_text='specialist category id from BMS')),
                ('auto', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('lastname', models.CharField(default=None, max_length=128, null=True)),
                ('avatar', models.CharField(default=None, max_length=1024, null=True)),
                ('username', models.CharField(max_length=128)),
                ('job', models.IntegerField()),
            ],
            options={
                'db_table': 'apps_specialist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_official', models.BooleanField(default=0)),
                ('status', models.SmallIntegerField(choices=[(-1, 'Banned'), (1, 'Profile filled'), (2, 'Verified')], default=0)),
                ('phone_activated', models.BooleanField(default=True)),
                ('enable_send_pvc', models.BooleanField(default=False)),
                ('is_related', models.BooleanField(default=False)),
                ('pvc', models.CharField(blank=True, max_length=150, null=True)),
                ('region_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('current_place', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_afgan', models.BooleanField(default=False)),
                ('is_cherno', models.BooleanField(default=False)),
                ('is_invalid', models.BooleanField(default=False)),
                ('is_uvu', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=255)),
                ('owner', models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=255)),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'apps_user',
                'managed': False,
            },
        ),
    ]
