# Generated by Django 5.0.6 on 2024-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_appproductcategorytranslate_appscategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsCategoryTranslate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'apps_categorytranslate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppsProductPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('discount', models.IntegerField()),
                ('active', models.BooleanField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('max_qty', models.IntegerField(blank=True, null=True)),
                ('min_qty', models.IntegerField(blank=True, null=True)),
                ('is_wholesale', models.BooleanField()),
            ],
            options={
                'db_table': 'apps_productprice',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('-order',), 'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='aboutusphoto',
            options={'ordering': ('-order',), 'verbose_name': 'About Us Photo', 'verbose_name_plural': 'About Us Photos'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('-order',), 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='contentphoto',
            options={'ordering': ('-order',), 'verbose_name': 'Content photo', 'verbose_name_plural': 'Content photos'},
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ('-order',), 'verbose_name': 'Legislative Base', 'verbose_name_plural': 'Legislative Bases'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ('-order',), 'verbose_name': 'Management', 'verbose_name_plural': 'Managements'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ('-order',), 'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
    ]
