from management.admin.politician import ManagementSortableModelAdmin, ContentSortableModelAdmin
from management.admin.politician_handbook import AboutUsSortableModelAdmin, StructureSortableModelAdmin, LawSortableModelAdmin
from management.admin.utils import ContentPhotosInline
