FROM python:3.10-slim-buster
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

# Requirements are installed here to ensure they will be cached.
COPY requirements.txt /app/

RUN apt-get update -y
RUN apt-get -y install libev-dev libnss3
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/