version: '3.8'

services:
  t_med_server:
    image: t_med_server:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: t_med_server
    env_file: app/env/.env.prod
    command: >
      /bin/bash -c "
      set -o errexit &&
      set -o pipefail &&
      set -o nounset &&
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "192.168.88.253:5001:8000"