version: '3.8'

services:
  t_med_server:
    image: t_med_server:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: t_med_server
    env_file: app/.env/.env.prod
    command: /app/app/compose/django/start
    restart: unless-stopped
    volumes:
      - .:/app/
    ports:
      - "5001:8000"