version: '3.8'

services:
  t_med_server:
    image: t_med_server:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: t_med_server
    env_file: app/env/.env.prod
    command: >
      /bin/bash -c "
      set -o errexit &&
      set -o pipefail &&
      set -o nounset &&
      cp -r /app/app/static/* /app/static/ &&
      python app/manage.py collectstatic --noinput &&
      python app/manage.py makemigrations &&
      python app/manage.py migrate &&
      python app/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/app
      - static_volume:/app/app/static
      - media_volume:/app/app/media
    ports:
      - "192.168.88.253:5001:8000"
     # - "5001:8000"

volumes:
  static_volume:
  media_volume: