version: '3.8'

services:
  t_med_server:
    image: t_med_server:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: t_med_server
    env_file: app/env/.env.prod
    command: /start
    restart: unless-stopped
    volumes:
      - .:/app/shared/django/
    ports:
      - "192.168.88.253:5001:8000"