from management.serializers.politician import ManagementSerializer, ContentListModelSerializer, ContentDetailModelSerializer
from management.serializers.politician_handbook import AboutUsSerializer, StructureSerializer, LawSerializer
