from management.serializers.politician import ManagementSerializer, PostListModelSerializer, PostDetailModelSerializer
from management.serializers.politician_handbook import AboutUsSerializer, StructureSerializer, LawSerializer
