# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import product_pb2 as product__to__org_dot_product__pb2


class ProductToOrganizationControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/product.ProductToOrganizationController/List',
                request_serializer=product__to__org_dot_product__pb2.ProductToOrganizationListRequest.SerializeToString,
                response_deserializer=product__to__org_dot_product__pb2.ProductToOrganizationListResponse.FromString,
                )
        self.SetRemainsProduct = channel.unary_unary(
                '/product.ProductToOrganizationController/SetRemainsProduct',
                request_serializer=product__to__org_dot_product__pb2.SetRemainsProductRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ReturnRemainsProduct = channel.unary_unary(
                '/product.ProductToOrganizationController/ReturnRemainsProduct',
                request_serializer=product__to__org_dot_product__pb2.ReturnRemainsProductRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ProductFind = channel.unary_stream(
                '/product.ProductToOrganizationController/ProductFind',
                request_serializer=product__to__org_dot_product__pb2.ProductIdRequest.SerializeToString,
                response_deserializer=product__to__org_dot_product__pb2.ProductToOrganizationListResponse.FromString,
                )
        self.ListDependentProduct = channel.unary_stream(
                '/product.ProductToOrganizationController/ListDependentProduct',
                request_serializer=product__to__org_dot_product__pb2.DependentProductListRequest.SerializeToString,
                response_deserializer=product__to__org_dot_product__pb2.DependentProduct.FromString,
                )


class ProductToOrganizationControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRemainsProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnRemainsProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProductFind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDependentProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductToOrganizationControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=product__to__org_dot_product__pb2.ProductToOrganizationListRequest.FromString,
                    response_serializer=product__to__org_dot_product__pb2.ProductToOrganizationListResponse.SerializeToString,
            ),
            'SetRemainsProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRemainsProduct,
                    request_deserializer=product__to__org_dot_product__pb2.SetRemainsProductRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ReturnRemainsProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnRemainsProduct,
                    request_deserializer=product__to__org_dot_product__pb2.ReturnRemainsProductRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ProductFind': grpc.unary_stream_rpc_method_handler(
                    servicer.ProductFind,
                    request_deserializer=product__to__org_dot_product__pb2.ProductIdRequest.FromString,
                    response_serializer=product__to__org_dot_product__pb2.ProductToOrganizationListResponse.SerializeToString,
            ),
            'ListDependentProduct': grpc.unary_stream_rpc_method_handler(
                    servicer.ListDependentProduct,
                    request_deserializer=product__to__org_dot_product__pb2.DependentProductListRequest.FromString,
                    response_serializer=product__to__org_dot_product__pb2.DependentProduct.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductToOrganizationController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductToOrganizationController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/product.ProductToOrganizationController/List',
            product__to__org_dot_product__pb2.ProductToOrganizationListRequest.SerializeToString,
            product__to__org_dot_product__pb2.ProductToOrganizationListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRemainsProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductToOrganizationController/SetRemainsProduct',
            product__to__org_dot_product__pb2.SetRemainsProductRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReturnRemainsProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductToOrganizationController/ReturnRemainsProduct',
            product__to__org_dot_product__pb2.ReturnRemainsProductRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProductFind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/product.ProductToOrganizationController/ProductFind',
            product__to__org_dot_product__pb2.ProductIdRequest.SerializeToString,
            product__to__org_dot_product__pb2.ProductToOrganizationListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDependentProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/product.ProductToOrganizationController/ListDependentProduct',
            product__to__org_dot_product__pb2.DependentProductListRequest.SerializeToString,
            product__to__org_dot_product__pb2.DependentProduct.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
